"""add manager_id to employees

Revision ID: 34779e4d01b3
Revises: 22e0e6d93c55
Create Date: 2026-09-02 23:03:22.833013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34779e4d01b3'
down_revision: Union[str, Sequence[str], None] = '22e0e6d93c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'employees', 'employees', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'manager_id')
    # ### end Alembic commands ###
