"""create attendance_logs table

Revision ID: 3beb3313edb3
Revises: 26f9cce1c1a8
Create Date: 2026-09-30 23:14:23.738219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3beb3313edb3'
down_revision: Union[str, Sequence[str], None] = '26f9cce1c1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('clock_in_at', sa.DateTime(), nullable=False),
    sa.Column('clock_out_at', sa.DateTime(), nullable=True),
    sa.Column('geofence_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('geofence_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_logs_employee_id'), 'attendance_logs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_logs_org_id'), 'attendance_logs', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_logs_org_id'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_employee_id'), table_name='attendance_logs')
    op.drop_table('attendance_logs')
    # ### end Alembic commands ###
