"""add geofence fields to org_units

Revision ID: 9efdcb921946
Revises: 3beb3313edb3
Create Date: 2026-10-01 06:34:37.110178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efdcb921946'
down_revision: Union[str, Sequence[str], None] = '3beb3313edb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_units', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('org_units', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('org_units', sa.Column('allowed_radius_meters', sa.Integer(), nullable=False, server_default='150'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_units', 'allowed_radius_meters')
    op.drop_column('org_units', 'longitude')
    op.drop_column('org_units', 'latitude')
    # ### end Alembic commands ###
